AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sagemaker-api

Globals:
  Function:
    Timeout: 10 
    MemorySize: 256
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  SageMakerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: llm_lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT: "huggingface-pytorch-tgi-inference-2025-04-19-18-06-41-327"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - "sagemaker:InvokeEndpoint"
              Resource: "*"
      Events:
        PredictApi:
          Type: Api
          Properties:
            Path: /predict
            Method: post

Outputs:
  PredictApi:
    Description: API Gateway endpoint URL for invoking the SageMaker function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  SageMakerFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt SageMakerFunction.Arn
  SageMakerFunctionRole:
    Description: IAM Role for SageMaker Lambda
    Value: !GetAtt SageMakerFunctionRole.Arn
